/**
 * First Appeal text generator — Section 19(1) of the RTI Act, 2005.
 * Uses real RTI data; generates a polished, field-ready appeal draft.
 */
import { formatFriendlyDate } from './deadline'

export interface AppealInput {
  authority_name: string
  original_query: string
  final_request: string
  registration_number: string | null
  submitted_at: string | null
  response_due_at: string | null
  applicant: { name: string; email: string; phone: string } | null
  days_overdue: number
  demo_now: string | null
}

export function generateAppealText(data: AppealInput): string {
  const filedDate  = data.submitted_at    ? formatFriendlyDate(data.submitted_at)    : '[filing date]'
  const dueDate    = data.response_due_at ? formatFriendlyDate(data.response_due_at) : '[due date]'
  const todayDate  = formatFriendlyDate(data.demo_now ?? new Date().toISOString())
  const regNum     = data.registration_number ?? '[Registration Number]'
  const name       = data.applicant?.name  ?? '[Applicant Name]'
  const phone      = data.applicant?.phone ?? '[Phone]'
  const email      = data.applicant?.email ?? '[Email]'
  const overdueDays = data.days_overdue

  return `FIRST APPEAL UNDER SECTION 19(1) OF THE RIGHT TO INFORMATION ACT, 2005

Date: ${todayDate}

To,
The First Appellate Authority,
${data.authority_name},
[Address — verify before submission]

Subject: First Appeal against non-receipt of information — RTI Application No. ${regNum}

Respected Sir/Madam,

1.  BACKGROUND

I, ${name}, filed an RTI application bearing Registration No. ${regNum} dated ${filedDate} with the Central Public Information Officer (CPIO), ${data.authority_name}, seeking the following information:

    "${data.original_query}"

2.  NON-RECEIPT OF RESPONSE

The statutory period of 30 (thirty) days as prescribed under Section 7(1) of the Right to Information Act, 2005 expired on ${dueDate}. As on the date of this First Appeal, ${overdueDays} day(s) have elapsed beyond the prescribed limit and no response — granting, refusing, or seeking a transfer — has been received from the CPIO.

Non-furnishing of information within the prescribed period constitutes a deemed refusal as per Section 7(2) of the RTI Act, 2005.

3.  GROUNDS FOR APPEAL

    (a) The CPIO has failed to furnish the requested information within the 30-day time limit mandated by Section 7(1) of the RTI Act, 2005.

    (b) No communication citing any exemption under Sections 8 or 9 of the Act has been received, nor any intimation of an extension under Section 7(3).

    (c) The information sought relates to public records held by a public authority and does not, to the best of my knowledge, attract any exemption under the Act.

4.  RELIEF SOUGHT

In view of the foregoing, I most respectfully pray that this Hon'ble First Appellate Authority may be pleased to:

    (a) Direct the CPIO, ${data.authority_name}, to provide the complete information sought in the original RTI application forthwith;

    (b) Impose a penalty on the CPIO under Section 20(1) of the RTI Act, 2005 for failure to furnish information within the prescribed time limit; and

    (c) Pass such other orders as this Hon'ble Authority may deem fit and proper in the interest of transparency and accountability.

This appeal is being filed within the period prescribed under Section 19(1) of the RTI Act, 2005.

Yours faithfully,

Name:  ${name}
Phone: ${phone}
Email: ${email}
Date:  ${todayDate}

Enclosures:
  1. Copy of original RTI application dated ${filedDate} (Reg. No. ${regNum})
  2. Proof of submission / acknowledgement slip

──────────────────────────────────────────────────────────────────────
PROTOTYPE NOTICE: This First Appeal was generated by RTI Navigator
(hackathon demo). Please review every field carefully and verify the
First Appellate Authority's address before filing. This document has
no legal standing until verified and submitted through official channels.
──────────────────────────────────────────────────────────────────────`
}
